sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
  - secure: TTePse78H4PU/SUFd25C/ArPAj3PDdRBc9+ZBOvsH5IdM/0I04HMwzvHi0A+kNL8QtX94OZ+HKMT/o3odM4FB1E3EneCr/uuXNagsErDdUN8J+7DNdTa5tEdDft9qr/TRFWsN5I1qfuyVwgMqd64/nG3kwjQnVhDvUM6dqZKYl5cJY9QKM+FF1YOc7+xDhvQjF5Hc5Fzei2DtthA4b3XwqenUxLmrcfOlh8aL83R+wR/TSiI05I3506XM/kfYxXKMILzrM8h9/ykE176cRL8Wa/XHnordCkIFRsYDeytmyDF0w6qp7lqHT1I6xumjzItGscxaJO/5zPURh2ieZawOSivxR/wzgYkH41oMvC/0yAbJyRH+he3uqnjI7LBLzFJ+EgyLpf2VVcn40mChjt5hPPK+u8La+zUaPWexkUdFXIGwO2yWD/ytyVoLvniMMJNY4ZriuBdfh/2hOWQw/WpYVvhXG/PV+03hgpiWNhAUlcGkxE9RwViADjonuNI2raxf+eXTkqH/6a8AXCybV2YMsBEghgATCVUQRM77uJNIjIkVJFqUVdT+wzVZke/wLGSyX/R98JqxA0pEZK2jarYZ21NK6Kq5k3fHOANJz9wJlEeq1+IPiHW++CMLSWvoDAijGQKdklBU+FLtSVq6x704c8w8r9xtuKSM7sZX2cjbtI=
  - secure: kDAf5+z/1izRxe1D5a12mT6x4pjkJF4nTTLIyGnbizTZsOOXVa4vNGTilVvExbhT1pmKIE0NK8kTNSj3QOx+jwYxdaa1ecQN72gFl7JRDeO5E1jMSIdmiB+qnJQH1xRoQDprcEy3OpAU1jDbrRL983tcok4JJkFlY1nIklSo7ZHDullXrrTokFaPgquty/wEDypCqPAtVMQGTkdk+3QcONwjo8onP/dRls3B+ZgBy4AbYCgtv5B8yDxV2mHXaYJAeoMfnvKPgjeLZ3+gfApN6HHQ9FF7NitT6EBjco0F68pA1msRzn/MdYoILhpXH9fLje/6L91zCh2fRfI3VaWaZ12cx51BhHp1/4WaY39Yv/zhA0/QPMhbn8DWrKNL85Z2L2iti5Q68zdjX3SO7t3S3ZH7FUJ8RNalFWb1Ln9SmSTMVzkDTy1gjqo12G6bnEj0lKs/tOj/dJzshZFhSWvlDZ4/g/t9ILug9rXivKm9XXwj4VShs22BEw0bVSF/I3WQk2ItGEbqQ7sMhfeHmfYlqD6d+KmS/ajJH5ucn0L7Dl77rIQuSM0UvEvBAzvMx6V54PQT/HSbtqOq4mX2T29Bx7UktWCE7DzEZRSle70IM65/Cdkhi9O/IiZlci+8CkWU2kiHCu5H8LfdnxSyqFQ5dcTQwBJXTJ9RLIuiQjyfCV8=
