sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: TTePse78H4PU/SUFd25C/ArPAj3PDdRBc9+ZBOvsH5IdM/0I04HMwzvHi0A+kNL8QtX94OZ+HKMT/o3odM4FB1E3EneCr/uuXNagsErDdUN8J+7DNdTa5tEdDft9qr/TRFWsN5I1qfuyVwgMqd64/nG3kwjQnVhDvUM6dqZKYl5cJY9QKM+FF1YOc7+xDhvQjF5Hc5Fzei2DtthA4b3XwqenUxLmrcfOlh8aL83R+wR/TSiI05I3506XM/kfYxXKMILzrM8h9/ykE176cRL8Wa/XHnordCkIFRsYDeytmyDF0w6qp7lqHT1I6xumjzItGscxaJO/5zPURh2ieZawOSivxR/wzgYkH41oMvC/0yAbJyRH+he3uqnjI7LBLzFJ+EgyLpf2VVcn40mChjt5hPPK+u8La+zUaPWexkUdFXIGwO2yWD/ytyVoLvniMMJNY4ZriuBdfh/2hOWQw/WpYVvhXG/PV+03hgpiWNhAUlcGkxE9RwViADjonuNI2raxf+eXTkqH/6a8AXCybV2YMsBEghgATCVUQRM77uJNIjIkVJFqUVdT+wzVZke/wLGSyX/R98JqxA0pEZK2jarYZ21NK6Kq5k3fHOANJz9wJlEeq1+IPiHW++CMLSWvoDAijGQKdklBU+FLtSVq6x704c8w8r9xtuKSM7sZX2cjbtI=
