---
upload_path: "/assets/images/uploads"
frontmatter_file_url_template: "/assets/images/uploads"
body_file_url_template: "/assets/images/uploads"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
