---
label: Core Values
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: ''
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- type: file
  name: cover
  label: Cover
- name: author
  label: Author
  type: text
  hidden: false
  default: ''
- name: navigation
  label: Navigation
  type: boolean
  hidden: false
  default: ''
- name: class
  label: Class
  type: text
  hidden: false
  default: ''
- name: comments
  label: Comments
  type: boolean
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: ''
- name: permalink
  label: Permalink
  type: text
  hidden: false
  default: ''
- name: group
  label: Group
  type: text
  hidden: false
  default: ''
- name: group-order
  label: Group order
  type: text
  hidden: false
  default: ''
pages:
- _pages/academy/objectives/okrs-vs-goals.md
- _pages/academy/objectives/okrs-vs-kpis.md
- _pages/academy/vision/big-hairy-audacious-goals/envisioned-future.md
- _pages/academy/vision/personal-vision-statement-examples/index.md
- _pages/academy/vision/personal-vision-statement/index.md
- _pages/academy/vision/core-values/index.md
